### ISSUE TITLE
Avoid 6 jumps in Tor

### ISSUE THREAD

**Issue by knlnlo** [brainfucksec/archtorify#11]
Torproject does not recommend using any other browser other than the Tor Browser. However, when you enable archtorify
and Tor Browser we get six hops instead of three. To avoid this, you need to set environment variables and create user.js in the Tor Browser directory. You can find out the details [here](https://www.whonix.org/wiki/Other_Operating_Systems#Configure_Tor_Browser_Settings). I think you need to implement this in archtorify.

Thanks.

**Comment by brainfucksec** [comment]
This argument is covered in the Wiki, see: [Security:Transparent Proxy with archtorify and Tor Browser](https://github.com/brainfucksec/archtorify/wiki/Security#transparent-proxy-with-archtorify-and-tor-browser).

archtorify does not set does not set Tor over Tor by default, and does not modify Tor Browser, Firefox or other Browsers.
Anyway this section needs to be extended in the Wiki.

**Comment by knlnlo** [comment]
It is because archtorify does not change the Tor Browser settings that we get Tor Over Tor. It must change the Tor Browser settings to avoid six hops instead of three.

**Comment by brainfucksec** [comment]
hi @knlnlo
This script does not and cannot change settings of other applications like Tor Browser or Firefox.

**Comment by z36r2850o** [comment]
@brainfucksec

I don't understand your position! These are the necessary settings for working with the Tor network! The script can and should be taught to change these settings!

**Comment by z36r2850o** [comment]
https://www.ghacks.net/2018/11/26/can-you-use-the-tor-browser-without-tor-connection/

Here (at the very bottom) settings are published and constantly updated to disable the Tor network in the browser itself in order to use the Tor system daemon and avoid Tor over Tor.

All we need is to find the path to the profile and create files with settings in it, and delete them when disconnecting from the Tor network.
